#!/usr/bin/env bash
# platform-reader.sh — defensive parser for a project's PLATFORM.md contract.
#
# PLATFORM.md is auto-generated by ai-platform-operator and is the source of truth
# for a provisioned project (namespace, registry, secrets, OTLP endpoint, URLs).
# Its exact wording and section order drift over time, so this reader couples to
# SEMANTICS (section headers + anchor labels), never to line numbers.
#
# Usage:
#   platform-reader.sh [FILE|DIR]
#     no arg  -> search for PLATFORM.md from $PWD upward
#     DIR     -> search from DIR upward
#     FILE    -> parse that file directly
#
# Output (stdout): shell-evalable key='value' lines. Consume with:
#   eval "$(platform-reader.sh)"
#   echo "$registry $namespace ..."
# Keys: provisioned namespace registry deploy_secret_name db_secret_name
#       mongodb_secret_name mysql_secret_name redis_secret_name bucket_secret_name otlp_endpoint
#       ingress_url grafana_url resource_quota
#
# Exit codes:
#   0  provisioned — PLATFORM.md found and parsed
#   3  not provisioned yet — placeholder or no PLATFORM.md (NOT an error)
#   2  usage error
#
# Degradation contract: a missing section yields an empty value, never a crash.
# Unknown sections are ignored.

set -u

usage() {
  # print the leading comment block only (stop at first code line)
  awk 'NR>1 { if ($0 ~ /^#/) { sub(/^# ?/,""); print } else if ($0=="") next; else exit }' "$0"
  exit 2
}

[ "${1:-}" = "-h" ] || [ "${1:-}" = "--help" ] && usage

# --- locate PLATFORM.md ------------------------------------------------------
find_platform() {
  local start="${1:-$PWD}" dir
  if [ -f "$start" ]; then printf '%s' "$start"; return 0; fi
  [ -d "$start" ] || start="$(dirname "$start")"        # arg may be a non-existent path
  # absolutize: a relative start makes dirname collapse to "." and loop forever
  dir="$(cd "$start" 2>/dev/null && pwd)" || return 1
  while [ -n "$dir" ]; do
    if [ -f "$dir/PLATFORM.md" ]; then printf '%s' "$dir/PLATFORM.md"; return 0; fi
    [ "$dir" = "/" ] && break
    dir="$(dirname "$dir")"
  done
  return 1
}

# --- field extraction --------------------------------------------------------
# _field SECTION_KEYWORD ANCHOR_LABEL  (both lowercase substrings)
# Prints the first body line inside the matching "## <section>" that contains
# the anchor label. Section ends at the next "## " header. Subsections ("### ")
# stay inside the parent section.
_field() {
  awk -v sec="$1" -v anc="$2" '
    { l = tolower($0) }
    /^## / { inSec = (index(l, sec) > 0) ? 1 : 0; next }
    inSec == 1 {
      p = index(l, anc)
      if (p > 0) {
        # the char before the anchor must be a non-word char, so anchor "name:"
        # matches "- Name:" but not "username:"/"hostname:"
        before = (p == 1) ? " " : substr(l, p - 1, 1)
        if (before !~ /[a-z0-9]/) { print $0; exit }
      }
    }
  ' "$FILE"
}

# _clean RAW_LINE -> value: drop label up to first colon, trim, prefer a
# backtick-quoted token if present (e.g. `demo-db-credentials`).
_clean() {
  local v
  # tr -d '\r' guards against CRLF PLATFORM.md (trailing \r would break curl etc.)
  v="$(printf '%s' "$1" | tr -d '\r' | sed -e 's/^[^:]*://')"
  v="$(printf '%s' "$v" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
  case "$v" in
    *'`'*) v="$(printf '%s' "$v" | sed -e 's/^[^`]*`//' -e 's/`.*$//')" ;;
  esac
  printf '%s' "$v"
}

field() { _clean "$(_field "$1" "$2")"; }

# _emit NAME VALUE -> shell-evalable single-quoted assignment
_emit() {
  local esc
  esc="$(printf '%s' "$2" | sed "s/'/'\\\\''/g")"
  printf "%s='%s'\n" "$1" "$esc"
}

# --- main --------------------------------------------------------------------
FILE="$(find_platform "${1:-}")" || {
  _emit provisioned false
  exit 3
}

# Placeholder / unprovisioned files carry no "## " section headers.
# (grep -c prints "0" and exits 1 on no match — capture stdout, ignore exit.)
header_count="$(grep -c '^## ' "$FILE" 2>/dev/null)"
[ -z "$header_count" ] && header_count=0
if [ "$header_count" -lt 1 ]; then
  _emit provisioned false
  exit 3
fi

_emit provisioned        true
_emit namespace          "$(field 'namespace'          'name:')"
_emit registry           "$(field 'container registry' 'registry:')"
_emit deploy_secret_name "$(field 'ci/cd'              'deploy secret:')"
_emit db_secret_name     "$(field 'database'           'credentials secret:')"
_emit mongodb_secret_name "$(field 'mongodb'           'credentials secret:')"
_emit mysql_secret_name  "$(field 'mysql'              'credentials secret:')"
_emit redis_secret_name  "$(field 'redis'              'credentials secret:')"
_emit bucket_secret_name "$(field 'object storage'     'credentials secret:')"
_emit otlp_endpoint      "$(field 'observability'      'endpoint:')"
_emit ingress_url        "$(field 'ingress'            'url:')"
_emit grafana_url        "$(field 'monitoring'         'dashboard:')"
_emit resource_quota     "$(field 'namespace'          'resourcequota:')"

exit 0
